version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: this
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017
      - 9229:9229

  mongo-express:
    image: mongo-express
    restart: always
    container_name: those
    ports:
      - 8111:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
