global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['api:3000', 'resources:3010'] # Adjust ports as needed
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
