global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bind'
    static_configs:
      - targets:
          - api:3000

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
