# Run Only Tasks Affected by a PR
name: LintTestBuild-CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: ./pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v3

      - run: |
          if [ ! -n "$(git show-ref refs/heads/main)" ]; then
            git branch --track main origin/main
          else
            echo "Branch 'main' already exists. Skipping branch creation."
          fi

      - run: pnpm i nx -g
      - run: nx affected:lint --fix --parallel
      - run: nx format:write
      - run: nx affected:test --parallel
      - run: nx affected:build --parallel
