name: LintTestBuildE2E-CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

  format_write:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run format:write
        run: nx affected -t format:write --parallel

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: nx affected -t test --parallel

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: nx affected -t build --parallel

  e2e:
    runs-on: ubuntu-latest
    needs: install-dependencies
    services:
      e2e-environment:
        image: docker/compose:1.29.2
        options: --privileged
        ports:
          - 3000:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run e2e tests
        run: nx affected -t e2e --parallel

  all-tasks:
    runs-on: ubuntu-latest
    needs: [ format_write, test, build, e2e ]
    steps:
      - name: Check status of all tasks
        run: echo "All tasks completed successfully."
